### ISSUE TITLE
Click on any tab and press F5 = 404 error

### ISSUE THREAD

**Issue by ZOXEXIVO** [damienbod/Angular2WebpackVisualStudio#44] opened 2016-12-29 18:37 UTC
SPA must be SPA

**Comment by robisim74** [comment] 2016-12-29 20:54
Fixed with the latest commit.

Thanks for reporting.

Greetings

**Comment by damienbod** [comment] 2016-12-30 11:52
Thanks

**Comment by ZOXEXIVO** [comment] 2017-01-03 09:13
Check it. Not working!

**Comment by damienbod** [comment] 2017-01-03 10:06
I'll have a look, thanks for the information.

Greetings Damien

**Comment by damienbod** [comment] 2017-01-03 10:23
Hi @ZOXEXIVO 

I tried this with the production build and with the dev build in IE and Chrome and do not have this problem.

1) build SPA
2) start app
3) select about menu
4) refresh => OK

How do you test, build, have you refreshed your cache, built the SPA?

Sorry if the questions sound dumb, I need more information

Greetings Damien

**Comment by damienbod** [comment] 2017-01-11 09:33
@ZOXEXIVO I'm closing this, cannot reproduce.

**Closed by damienbod** 2017-01-11 09:33 UTC
